language: node_js
node_js:
  - 12
cache: npm
notifications:
  email: false
before_install:
  - npm install -g codecov
script:
  - DEBUG= make docker-test
  - codecov
branches:
  except:
    - '/^v\d+\.\d+\.\d+$/'
jobs:
  include:
    - stage: deploy
      if: branch == master && !fork
      node_js: 'node'
      script:
        - npm install -g semantic-release@^15
        - semantic-release